/**
 * Copyright (c) 2014-present, Facebook, Inc. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *      
 */

                                                       
                                 
                                          
                                               
                                 
                              
                                                      
                                                      
                                      
                                                      
                                                                   
                                 
                             // Since in JS anything can be thrown as an error.
                                     // String representation of error.
                    
                        
             
                 
                        
                   
  

                                                                

                   
      
                                              
      
      
                            
                      
                                        
                           
      
      
                      
                                         
                           
      
      
                            
                       
                         
                 
                       
      
      
                            
                       
                         
                  
                      
                       
      
      
                         
                 
      
      
                           
                                    
                       
                 
      
      
                           
                                
                                    
                       
                 
      
      
                            
                      
      
      
                              
                      
      
      
                              
                       
                      
      
      
                                                                              
                                     
                         
                      
      
      
                        
                      
      
      
                                                                        
                                                                        
                                                                             
                                  
                        
                      
      
      
                                 
                                   
      
      
                                  
                                   
      
      
                        
      
      
                         
      
      
                                                                              
                            
                    
                       
      
      
                                                                       
                    
                               
                             
      
      
                                                                               
                                                                          
                       
       

                                         
                           
                    
                                
                     
                                              
                                        
   

                         
                                         
                           
  

                                            

                                   
                                                
                                                 
  

                      
                                      
                                                                              
                                            
                                                               
                                                                   
                                                                            
                       
                                                    
                                                                 
                                   
                           
                      
                                    
                                       
   

                              
                                 
                     
                  
                  
                         
                          
   

                                                             // the error from the test, as well as a backup error for async

                          
                                                                                   
                    
              
                 
                 
                        
                     
                    
                                                                          
                   
   
